### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by qzane** [TomTomTommi/bidavideo#3]
Hi, thanks for this great work on stereo depth estimation. Could you please add a LICENSE file for this project? Thank you so much!

**Comment by TomTomTommi** [comment]
Done.

**Comment by jowookoh** [comment]
Hey @TomTomTommi, thank you for this amazing work! I just wanted to check, is South Kensington Stereo Vision dataset also under MIT licence, available for commercail usage?

**Comment by TomTomTommi** [comment]
Hi, only the code is MIT license. SK dataset is under CC BY-NC-SA 4.0 license. Please check [link](https://github.com/TomTomTommi/bidavideo/blob/main/datasets/README.md) of the license in detail.

**Comment by jowookoh** [comment]
Thank you for the quick response!
